### PR TITLE
fix Travis-CI

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
same error on CI that I saw locally:

```
java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.dbuild#dbuild;0.9.17!
	at sbt.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:52)
	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
	at sbt.IvyActions$$anonfun$deliver$1.apply(IvyActions.scala:108)
	at sbt.IvyActions$$anonfun$deliver$1.apply(IvyActions.scala:103)
```

**Comment by dwijnand** [comment]
Run `update` (to force it to run).  There's a weird thing that deliver relies on a file that update creates, and the caching can sometimes not trigger so it goes missing.  Maybe blow Travis CI's caches?  And is there a reason this is using Ivy not Coursier?

**Comment by SethTisue** [comment]
> Run update (to force it to run)

That didn't seem to help

> Maybe blow Travis CI's caches

I don't think so, I get the same error locally

> And is there a reason this is using Ivy not Coursier?

dbuild uses ancient versions of everything

**Comment by SethTisue** [comment]
I'm not going to pursue this further

**Pull request closed without merging**
