### PR TITLE
Wip/improve deugging tools

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by SethTisue** [comment]
9542f45984edebe2505df99c1dcf8d2b

**Comment by cunei** [comment]
What just happened? I don't even

**Comment by dwijnand** [comment]
There were two danging branches in the repo, so I opened them as PRs, so we don't lose the code, but we can delete the branch.

**Comment by SethTisue** [comment]
and also Dale misspelled "debugging"

**Comment by dwijnand** [comment]
Oh, lol.  No, didn't even notice.  😆   (It's derived from Josh's branch name.)

**Pull request closed without merging**
