### PR TITLE
prepare for 0.9.17 release

### PR DESCRIPTION
**Pull request by SethTisue**
references scala/community-build#1243

### CODE REVIEW

**Comment by SethTisue** [comment]
sigh, I don't know why Travis-CI isn't triggering

in any case, I ran the same commands locally... or rather I tried, `it:test` failed with `[error] (dist/*:deliverLocal) java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.dbuild#dbuild;0.9.17!`, idk why, `~/.ivy2/local/com.typesafe.dbuild/dbuild/0.9.17/ivys/ivy.xm` is present

I guess I'll go ahead and publish 0.9.17 anyway and see if it works in the community build

**Comment by SethTisue** [comment]
0.9.17 is published

**Comment by dwijnand** [comment]
> sigh, I don't know why Travis-CI isn't triggering

image

click the burger menu at https://travis-ci.org/github/lightbend/dbuild/requests 
image

**Comment by SethTisue** [comment]
thanks Dale, that was exactly the clue I needed! #230

**Pull request merged**
